
function encrypted_hdl_import_wrapper_config(this_block)

  % Revision History:
  %
  %   16-Jul-2009  (16:43 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     K:\ipexport\mvi\ccm\v_src\encrypted_hdl_import_wrapper.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('encrypted_hdl_import_wrapper');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('video_data_in');
  this_block.addSimulinkInport('active_video_in');
  this_block.addSimulinkInport('hblank_in');
  this_block.addSimulinkInport('sclr');
  this_block.addSimulinkInport('vblank_in');


  this_block.addSimulinkOutport('video_data_out');
  this_block.addSimulinkOutport('active_video_out');
  this_block.addSimulinkOutport('hblank_out');
  this_block.addSimulinkOutport('vblank_out');

  video_data_out_port = this_block.port('video_data_out');
  video_data_out_port.setType('UFix_24_0');
  active_video_out_port = this_block.port('active_video_out');
  active_video_out_port.setType('UFix_1_0');
  active_video_out_port.useHDLVector(false);
  hblank_out_port = this_block.port('hblank_out');
  hblank_out_port.setType('UFix_1_0');
  hblank_out_port.useHDLVector(false);
  vblank_out_port = this_block.port('vblank_out');
  vblank_out_port.setType('UFix_1_0');
  vblank_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('active_video_in').width ~= 1);
      this_block.setError('Input data type for port "active_video_in" must have width=1.');
    end

    this_block.port('active_video_in').useHDLVector(false);

    if (this_block.port('hblank_in').width ~= 1);
      this_block.setError('Input data type for port "hblank_in" must have width=1.');
    end

    this_block.port('hblank_in').useHDLVector(false);

    if (this_block.port('sclr').width ~= 1);
      this_block.setError('Input data type for port "sclr" must have width=1.');
    end

    this_block.port('sclr').useHDLVector(false);

    if (this_block.port('vblank_in').width ~= 1);
      this_block.setError('Input data type for port "vblank_in" must have width=1.');
    end

    this_block.port('vblank_in').useHDLVector(false);

    if (this_block.port('video_data_in').width ~= 24);
      this_block.setError('Input data type for port "video_data_in" must have width=24.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('encrypted_hdl_import.vhd','encrypted_hdl_import.vhd');
  this_block.addFile('encrypted_hdl_import_wrapper.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

