
function cordic_sincos_config(this_block)

  % Revision History:
  %
  %   26-Jan-2009  (15:11 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\To_Nabeel\coregen_import\example1\cordic_sincos.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('cordic_sincos');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('phase_in');

  this_block.addSimulinkOutport('x_out');
  this_block.addSimulinkOutport('y_out');
  this_block.addSimulinkOutport('rdy');

  x_out_port = this_block.port('x_out');
  x_out_port.setType('UFix_16_0');
  y_out_port = this_block.port('y_out');
  y_out_port.setType('UFix_16_0');
  rdy_port = this_block.port('rdy');
  rdy_port.setType('UFix_1_0');
  rdy_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('phase_in').width ~= 16);
      this_block.setError('Input data type for port "phase_in" must have width=16.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('cordic_sincos.vhd');
  this_block.addFile('cordic_sincos.ngc');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

