function FileData_Pairs(x)
{
x.t("available","adobe");
x.t("version","documentation");
x.t("files","found");
x.t("user","guide");
x.t("pdf","version");
x.t("pdf","format");
x.t("pdf","versions");
x.t("open","pdf");
x.t("adobe","pdf");
x.t("sysgen_tree","/help/pdf_doc");
x.t("getting","started");
x.t("found","sysgen_tree");
x.t("list","getting");
x.t("browse","location");
x.t("guide","reference");
x.t("dsp","book");
x.t("alternatively","following");
x.t("matlab","alternatively");
x.t("started","user");
x.t("format","files");
x.t("book","list");
x.t("reference","guide");
x.t("documentation","available");
x.t("documentation","pdf");
x.t("documentation","system");
x.t("generator","dsp");
x.t("generator","documentation");
x.t("location","matlab");
x.t("/help/pdf_doc","browse");
x.t("system","generator");
x.t("following","links");
x.t("links","open");
x.t("versions","documentation");
}
