function FileData_Pairs(x)
{
x.t("token","design");
x.t("provide","1000x");
x.t("hardware","co-simulation");
x.t("hardware","platforms");
x.t("hardware","simulation");
x.t("hardware","co-simulate");
x.t("co-simulation","hardware");
x.t("co-simulation","introduction");
x.t("co-simulation","system");
x.t("create","hardware");
x.t("platforms","hardware");
x.t("introduction","hardware");
x.t("xilinx","dsp");
x.t("automatically","create");
x.t("dsp","blockset");
x.t("performance","increase");
x.t("provides","accelerated");
x.t("rest","simulink");
x.t("supported","hardware");
x.t("accelerated","simulation");
x.t("design","captured");
x.t("1000x","simulation");
x.t("simulink","system");
x.t("generator","automatically");
x.t("generator","provides");
x.t("captured","xilinx");
x.t("system","provide");
x.t("system","generator");
x.t("simulation","token");
x.t("simulation","hardware");
x.t("simulation","performance");
x.t("run","supported");
x.t("blockset","run");
x.t("co-simulate","rest");
}
