$[memmap_info.fromregs,memmap_info.toregs]:{'sm_$it.name$_dout' => $it.n_bits$,};separator="\n"$
$memmap_info.fromfifos:{'sm_$it.name$_dout' => $it.n_bits$,
'sm_$it.name$_pfull' => $it.percent_nbits$,
'sm_$it.name$_empty' => 0,};separator="\n"$
$memmap_info.tofifos:{'sm_$it.name$_pfull' => $it.percent_nbits$,
'sm_$it.name$_full' => 0,};separator="\n"$
$memmap_info.shmems:{'sm_$it.name$_dout' => $it.n_bits$,};separator="\n"$
